name: wall_e
description: Wallpaper Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.1
  image_gallery_saver: ^1.6.9
  flutter_bloc: ^7.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    
  fonts:
    - family: Comfortaa
      fonts:
        - asset: google_fonts/Comfortaa-Regular.ttf

flutter_icons:
  image_path: "assets/icon/appIcon.ico"
  android: true
  ios: true
